PUT http://localhost:6000/api/apparel/update
Content-Type: application/json
x-vendor-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkxMDNmYTA4LWQxMmEtNDY5ZS1hMDk0LTkyODM2MThkOWZhYyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjcyOTE5LCJleHAiOjE3NDAyNzY1MTl9.xrhtpASMRWtRfTHeZ0KCwSEPLJoFq9_Rk4-MzF2dFD4

{
  "code": "SHO-77340-9622",
  "name": "New Apparel Name",
  "variants": [
    {
      "sizeId": "XL-609140-22C9",
      "size": "Medium"
    }
  ]
}

###
POST http://localhost:6000/api/apparel/add
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkxMDNmYTA4LWQxMmEtNDY5ZS1hMDk0LTkyODM2MThkOWZhYyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjcyOTE5LCJleHAiOjE3NDAyNzY1MTl9.xrhtpASMRWtRfTHeZ0KCwSEPLJoFq9_Rk4-MzF2dFD4

{
  "name": "Shoes",
  "totalQuantity": 50,
  "variants": [
    {
      "size": "XL", 
      "quantity": 10,
      "price": 100.99
    }
  ]
}

###
GET http://localhost:6000/api/apparel
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxN2RlMDAwLWFhN2YtNGEzNi1iYjEyLTQ0ODVlNTM0ZDQ2NyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjM2NTk1LCJleHAiOjE3NDAyNDAxOTV9.FyINm6wl7-kmNrfRR8ayaOV2hzVmpU22XeOYkH5uhr4

###
GET http://localhost:6000/api/apparel/SHO-09140-7A69
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxN2RlMDAwLWFhN2YtNGEzNi1iYjEyLTQ0ODVlNTM0ZDQ2NyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjM2NTk1LCJleHAiOjE3NDAyNDAxOTV9.FyINm6wl7-kmNrfRR8ayaOV2hzVmpU22XeOYkH5uhr4

###
POST http://localhost:6000/api/order/create-single-order
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxN2RlMDAwLWFhN2YtNGEzNi1iYjEyLTQ0ODVlNTM0ZDQ2NyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjM2NTk1LCJleHAiOjE3NDAyNDAxOTV9.FyINm6wl7-kmNrfRR8ayaOV2hzVmpU22XeOYkH5uhr4

{
  "customerName": "Olaniyi Gideon Olamide",
  "items": [
    {
      "apparelCode": "SHO-74333-323B", 
      "sizeId": "XL-974334-E416",
      "quantity": 10,
      "vendorId": "9103fa08-d12a-469e-a094-9283618d9fac"
    }
  ]
}

###
GET http://localhost:6000/api/vendor/orders
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkxMDNmYTA4LWQxMmEtNDY5ZS1hMDk0LTkyODM2MThkOWZhYyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjcyOTE5LCJleHAiOjE3NDAyNzY1MTl9.xrhtpASMRWtRfTHeZ0KCwSEPLJoFq9_Rk4-MzF2dFD4


###
GET http://localhost:6000/api/vendor/773248fe-7067-420a-8a26-199436b35af6/can-fulfil-order
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkxMDNmYTA4LWQxMmEtNDY5ZS1hMDk0LTkyODM2MThkOWZhYyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjcyOTE5LCJleHAiOjE3NDAyNzY1MTl9.xrhtpASMRWtRfTHeZ0KCwSEPLJoFq9_Rk4-MzF2dFD4

###
GET http://localhost:6000/api/vendor/773248fe-7067-420a-8a26-199436b35af6/lowest-cost
Content-Type: application/json
X-Vendor-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkxMDNmYTA4LWQxMmEtNDY5ZS1hMDk0LTkyODM2MThkOWZhYyIsImVtYWlsIjoib2xhbWlkZXNAZ21haWwuY29tIiwiaWF0IjoxNzQwMjcyOTE5LCJleHAiOjE3NDAyNzY1MTl9.xrhtpASMRWtRfTHeZ0KCwSEPLJoFq9_Rk4-MzF2dFD4


###
POST http://localhost:6000/api/auth/register
Content-Type: application/json

{
  "email": "olamid8es@gmail.com",
  "password": "password",
  "name": "77"
}

###
POST http://localhost:6000/api/auth/login
Content-Type: application/json

{
  "email": "olamides@gmail.com"

}

###
POST http://localhost:6000/api/auth/login
Content-Type: application/json

{
  "email": "olamides@gmail.com",
  "password": "password"
}